name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Node.js 20.x ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies 👨‍🔧
        working-directory: ./paulus-seo
        run: npm install

      - name: Build website 🔨
        working-directory: ./paulus-seo
        run: npm run build

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./paulus-seo/build
          # cname: example.com # 사용자 정의 도메인이 있는 경우 주석 해제
